# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6cb77512-76e4-451a-85cd-fe3a6427397e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6cb77512-76e4-451a-85cd-fe3a6427397e".device = "/dev/disk/by-uuid/6cb77512-76e4-451a-85cd-fe3a6427397e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/43F2-DF42";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-80f98bd2-cded-407a-a0fc-9bfbce219dfd"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
